export const productsList = [
  {
    name: "Laptop",
    description: "Powerful computing device for work and entertainment",
    price: 999.99,
    category: "Electronics",
    imageUrl: "../img/laptop.png",
  },
  {
    name: "Running Shoes",
    description: "Comfortable and durable shoes for jogging and exercise",
    price: 79.99,
    category: "Footwear",
    imageUrl: "../img/shoes.png",
  },
  {
    name: "Smartphone",
    description: "High-end mobile device with advanced features",
    price: 799.99,
    category: "Electronics",
    imageUrl: "../img/smartphone.png",
  },
  {
    name: "Coffee Maker",
    description: "Automatic coffee machine for brewing your favorite beverages",
    price: 149.99,
    category: "Appliances",
    imageUrl: "../img/percolator.png",
  },
  {
    name: "Wireless Headphones",
    description: "Noise-canceling headphones for an immersive audio experience",
    price: 129.99,
    category: "Electronics",
    imageUrl: "../img/headphones.png",
  },
  {
    name: "Backpack",
    description: "Stylish and functional backpack for daily use",
    price: 49.99,
    category: "Fashion",
    imageUrl: "../img/backpack.png",
  },
  {
    name: "Fitness Tracker",
    description: "Track your daily activities and monitor your health",
    price: 69.99,
    category: "Electronics",
    imageUrl: "../img/fitnesstracker.jpg",
  },
  {
    name: "Cookware Set",
    description: "High-quality set of pots and pans for your kitchen",
    price: 199.99,
    category: "Appliances",
    imageUrl: "../img/saucepans.jpg",
  },
  {
    name: "Gaming Console",
    description: "Entertainment system for playing video games",
    price: 299.99,
    category: "Electronics",
    imageUrl: "../img/videogameconsole.jpg",
  },
  {
    name: "Hiking Boots",
    description: "Durable boots for outdoor adventures and hiking",
    price: 129.99,
    category: "Footwear",
    imageUrl: "../img/walking-boots.png",
  },
  {
    name: "Smartwatch",
    description: "Wearable device with fitness and communication features",
    price: 149.99,
    category: "Electronics",
    imageUrl: "../img/apple.jpg",
  },
  {
    name: "Blender",
    description: "Versatile blender for making smoothies and shakes",
    price: 89.99,
    category: "Appliances",
    imageUrl: "../img/audio.jpg",
  },
  {
    name: "Sunglasses",
    description: "Stylish sunglasses for protection and fashion",
    price: 59.99,
    category: "Fashion",
    imageUrl: "../img/woodsunglasses.jpg",
  },
  {
    name: "Digital Camera",
    description: "Capture high-quality photos and videos with this camera",
    price: 449.99,
    category: "Electronics",
    imageUrl: "../img/camera.png",
  },
  {
    name: "Dumbbell Set",
    description: "Weights for strength training and fitness workouts",
    price: 39.99,
    category: "Fitness",
    imageUrl: "../img/dumbbells.jpg",
  },
  {
    name: "Toaster Oven",
    description: "Compact oven for toasting and baking",
    price: 79.99,
    category: "Appliances",
    imageUrl: "../img/toaster.jpg",
  },
  {
    name: "Leather Wallet",
    description: "Classy and durable wallet for carrying your essentials",
    price: 29.99,
    category: "Fashion",
    imageUrl: "../img/leatherwallet.jpg",
  },
  {
    name: "Wireless Mouse",
    description: "Convenient and ergonomic mouse for your computer",
    price: 29.99,
    category: "Electronics",
    imageUrl: "../img/mouse.jpg",
  },
  {
    name: "Yoga Mat",
    description: "Comfortable mat for yoga and other fitness activities",
    price: 24.99,
    category: "Fitness",
    imageUrl: "../img/yogamat.jpg",
  },
  {
    name: "Desk Lamp",
    description: "Adjustable lamp for brightening up your workspace",
    price: 34.99,
    category: "Appliances",
    imageUrl: "../img/desklamp.png",
  },
];
